### ISSUE TITLE
This is trash

### ISSUE THREAD

**Issue by ElCapor** [3UR/RCCService-ASPNET-API#1]
Trash + recorded and sent to roblox infosecs stupid russians

**Comment by 3UR** [comment]
LOL

**Comment by 3UR** [comment]
cry about it

**Comment by Lez1S** [comment]
wowwwwwwwwwww start crying

**Comment by 3UR** [comment]
> 

im assuming you're DanIll2#6241? the skid who claims to know asp but cant even doa simple asset url 😳 😆
